server:
  port: 8089
database:
  mongo:
    uri: ${DATABASE_URL}
    name: ${DATABASE_NAME}
spring:
  jackson:
    parser:
      allow-numeric-leading-zeros: true
cache:
  schedule:
    refreshCacheEveryXMilliseconds: 1200000
    expireCacheAfterXMilliseconds: 1800000



