# docker-compose.yml
version: '3.1'
services:
  habito-database:
    build: .
    user: root
    container_name: habito-mysql
    command: ["sh", "-c", "/tmp/init.sh && exec docker-entrypoint.sh mysqld --default-authentication-plugin=mysql_native_password"]
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      HABITO_ADMIN_PASSWORD: ${HABITO_ADMIN_PASSWORD}